### ISSUE TITLE
[8/15] 4GDHC Heating Central Plant Model

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#108]
Modelica side finished. 

* need to validate still.

**Comment by laurenklun** [comment]
@Helarga Hi Hagar, didn't get a chance to ask about this on the scrum yesterday. Does this one still need to be validated or can we close it now?

**Comment by Helarga** [comment]
> @Helarga Hi Hagar, didn't get a chance to ask about this on the scrum yesterday. Does this one still need to be validated or can we close it now?

Hay Lauren, not yet , still we need to validate it " in progress".
