### ISSUE TITLE
[6/30] 4GDHC District Network Model (Cooling Only)

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#109]
Who will take this on? Possibly CU?
Radial loop only right now. Address mesh or grid down the road. 

LBL has some existing models that might be a good starting place. 

Antoine first, then Nate and Nick to templatize

1. Loads
2. ETS
3. Network Model
4. Central Plant

Milestone demonstrated when we do it for a Time series building, one type of building.

**Comment by laurenklun** [comment]
@nllong  Did we get an example from LBL for this?

**Comment by nllong** [comment]
Not that I know of. @AntoineGautier ?

**Comment by AntoineGautier** [comment]
Example models in the feature branch [issue1769_examples5GDHC](https://github.com/lbl-srg/modelica-buildings/tree/issue1769_examples5GDHC) under `Applications.DHC.Examples.Combined.Generation5.Unidirectional.Examples` show how two-pipe networks can be represented with the base class `PartialDistribution2Pipe`. The examples are for 5GDHC but 4GDHC should not differ for what concerns the network. Only a simple loop is modeled though.
From our discussion in the last meeting, @JingWang-CUB will investigate if the same modeling framework can be used for more complex topologies.

**Comment by nllong** [comment]
Thanks @AntoineGautier. I think we were successful in making this work for the 4GDHC case. We are templatizing the full 4G district cooling system this week.
