### ISSUE TITLE
[9/23] Update system parameter schema with additional arugments

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#124]
The [system parameter schema](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/system_parameters/schema.json) needs to be extended to support the other data required, such as [these items](https://docs.google.com/document/d/1xoCnikqM43fpF11bSYsnVns1R5lZRRWdcVkse2u6so0/edit).

**Comment by laurenklun** [comment]
@vtnate Nate, did this one finish up last week? Let me know if I can close it. Thanks!

**Comment by vtnate** [comment]
@laurenklun No, don't close this yet. Looks like #172 still needs review and merging.
