### ISSUE TITLE
Can't find the Modelica-Building class for running

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#13]
When i run the testcase, i got errors, all related can not find the class Building, Medium, ..... They are all related to the Modelica Building Class. 
Solution: export MODELICAPATH=/home/your-user-name/modelica-buildings
The error file is attached. 
[failure_CanntFindModelicaBuildings.txt](https://github.com/urbanopt/geojson-modelica-translator/files/3833725/failure_CanntFindModelicaBuildings.txt)

**Comment by nllong** [comment]
This has been resolved. Make sure to have git-lfs installed before cloning modelica buildings library.
