### ISSUE TITLE
I got C compiling error

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#14]
The test case cannot be compiled, due to a C compiling issue.

The error file is attached: 
[failure_compiling_C.txt](https://github.com/urbanopt/geojson-modelica-translator/files/3833727/failure_compiling_C.txt)

**Comment by nllong** [comment]
This is related to not having the full Modelica Buildings Library checked out. Make sure to follow these instructions: 

https://github.com/urbanopt/geojson-modelica-translator#running-simulations

And most importantly, make sure to have git-lfs installed and configured when checking out the library.
