### ISSUE TITLE
Syntax error in requirements.txt

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#15]
Running `pip install -r requirements.txt` yields:

```
ERROR: Invalid requirement: 'requests=2.22.0' (from line 7 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

**Comment by nllong** [comment]
Oops. Just fixed with latest commit on [develop](https://github.com/urbanopt/geojson-modelica-translator/commit/557eba3e711a65ae13b1984afe48e0fba1518c61).
