### ISSUE TITLE
[9/7] HVAC - Modify Building Template

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#152]
new template will be simple and do everything outside the template.

**Comment by Helarga** [comment]
The modelica model for connecting the time series mass flow rates and temperatures to heating and cooling indirect ETS is here 
https://github.com/Helarga/modelica-buildings/blob/timeSeriesMassFlowRateTemperatures/Buildings/Applications/DHC/Loads/TimeSeriesMassFlow_Temp.mo
The csv file for the 4GDH&C has been generated by @amyeallen1 👍
