### ISSUE TITLE
[8/21] Propose refactor for main to_modelica method

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#167]
The model_connectors scripts have been leveraged however, the main to_modelica method is the proposed and desired entry point.

https://github.com/urbanopt/geojson-modelica-translator/blob/a9ebe62d0e9d3644ad0fb231c705b9f0a28ce580/geojson_modelica_translator/geojson_modelica_translator.py#L92

Decide how to refactor this method to handle the abstracting of loads, districts, and plants.

**Comment by vtnate** [comment]
Centralize `add_building` method from each model connector into the base class. Add buildings (thermal/electrical load information), districts, and plants to the scaffold. gmt.py shall be the clearinghouse that passes information from the scaffold to Modelica, which runs simulations and returns information to the scaffold.

@nllong would you like to clarify anything?

**Comment by nllong** [comment]
Sounds good. We have these tickets that are a result of this task:

#170, #169, #173

I would also loop in #166. The script needs to be made into a class, add some tests, and called when the data are CSV (not MOS).
