### ISSUE TITLE
Integrate Docker images to be more consistent with Ubuntu/Windows.

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#17]
Create a docker image to:
1. download/install support libraries for JModelica;
1. download/install JModelica;
1. download modelica-buildings-library
1. build/compile the geojson-translator
1. run the geojson-translator

**Comment by nllong** [comment]
Note that this docker image already handles steps 1, 2, and 3. The need is to simply mount the geojson-translator library and required files, then run a python command. 

There needs to be a CLI developed to run the geojson modelica translator before we make the docker container (see #21)

**Comment by nllong** [comment]
Issue #36 will run the models using Jmodelica in docker. If we need to run the geojson-modelica-translator using docker, then we should create another project and install this project as a dependent package. Closing for now.
