### ISSUE TITLE
[9/4] Break apart district and infinite sources from model_connectors

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#173]
Currently, when a model is created an entire modelica file is templated and converted to the resulting model. This has been an effective method for quick development and testing; however, there is a bunch of code that becomes redundant. This task will be to 

1) break up the infinite sources from the coupled building models. The infinite sources should be part of the "district/central plant", even if there is no distribution.
1) break up the district_system Modelica code to separate out the building models and this district models. The models need to be placed into their own directory.
1) refactor the district_system Modelica code to allow any model connector.
1) determine if there are other places to DRY the code (e.g., are there model_connector methods that should become part of the base class)

**Comment by laurenklun** [comment]
@nllong  can this one be closed?

**Comment by nllong** [comment]
indeed it can. Thanks!
