### ISSUE TITLE
[9/18] Templatize Time Series Loads that are delta T.mdot

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#178]
~heating indirect
part of the same test for #165~
The above is addressed in PR #182 and issue #165. This issue is about adding TimeSeriesMassFlow_Temp as a template, as Hagar writes below. Nate was mistaken when originally speaking about this.

**Comment by Helarga** [comment]
- templatize the modelica model that reads the time series data "TimeSeriesMassFlow_Temp".
- develop a python code dedicated to run the TimeSeriesMassFlow_Temp.mot.
-develop the py.test for this template.
