### ISSUE TITLE
Implement building mechanical systems 

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#18]
1. Pick a typical air-terminals. == confirm with Nick
1. make modelica air-terminal
1. add air-terminals to translator
1. translate air-terminals to modelica
1. integrate modelica air-terminal with modelica building model

**Comment by nllong** [comment]
Check with @AntoineGautier on how to best implement this.

**Comment by nllong** [comment]
I think we can close this for the time being. Objections?
