### ISSUE TITLE
UO SDK project to DES project

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#199]
Go from SDK project to a DES project. Scaffold out all the issues.

Need solution for: SDK has more inputs than the GeoJSON file, what to do with possible missing information.

**Comment by vtnate** [comment]
- List of required inputs/outputs, with examples: https://docs.google.com/document/d/1EIZVTfDLri3PbbCv5eHIBfdPFnGmMVXgNMPCGHoKi_U
- Actual examples of i/o files: https://drive.google.com/drive/folders/1IN7W1dljKgrz5KqoZj2QmlLrbe3ijL1O

**Comment by vtnate** [comment]
@nllong: @amyeallen1 was really knowledgeable and helpful. The current plan is to write a couple new OpenStudio measures (reusing what we can from the abandoned [urban-measures repo](https://github.com/NREL/openstudio-urban-measures)) to include `DistrictHeating` and `DistrictCooling` objects in the output from the SDK. That will give us consistent variables to read into the system_parameters files.

**Comment by amyeallen1** [comment]
Thanks, Nate! On further thought, I remembered that the URBANopt model articulation gem has a measure "Create Typical Building from Model" that allows one to set "District Heating" or "District Cooling" as a source for heating and cooling. This will accomplish what we would want to use the time series approach for modeling a building tied to a DES. Is this measure still compatible with the current SDK process? https://github.com/NREL/openstudio-model-articulation-gem/tree/develop/lib/measures/create_typical_building_from_model

@vtnate
