### ISSUE TITLE
Sim Exec: In Python add method to run UO-SDK CLI to generate Scenario.csv

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#209]
Solution running from the UO SDK CLI. 

https://docs.google.com/document/d/1yDa5WnKh9ehfGxBF-NapfCrypRuXciMFOeDjYOY_-8c/edit 

**Sim Exec (Python) - Make a CLI! Fits into the Server**

Simulate UO and Extract Data Method

- GeoJSON

- In Python add method to run UO-SDK CLI to generate Scenario.csv -- Nate

- In Python add method to run UO-SDK to simulate (OS based) -- Nate

- Path 1: Use Spawn or Path 2: Extract Timeseries

- Extract Sizing values from EnergyPlus and set in GeoJSON/System Parameters files  -- Nate / Amy

Create requirements.txt
`pip install openstudio`, OpenStudio::sql… -- Nate!

**Comment by vtnate** [comment]
Bullets 2 & 3 will be accomplished by the user interacting with the existing sdk cli. Once that is completed the user will switch to our `des_cli` for further district system analysis.
