### ISSUE TITLE
Sim Exec: Extract Sizing values from EnergyPlus and set in GeoJSON/System Parameters files

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#211]
Amy combining two measures to turn into 1
Then turn into gem that the SDK uses.

Nate building a new class for this process. 

https://docs.google.com/document/d/1yDa5WnKh9ehfGxBF-NapfCrypRuXciMFOeDjYOY_-8c/edit

**Comment by vtnate** [comment]
Going to use the measures written by @amyeallen1 in the sdk to produce the desired output.
