### ISSUE TITLE
[1/8/20] Draft of draft CU boulder case study

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#220]
https://drive.google.com/drive/folders/1nGkdjvPtYpikqntUZH9RNClLbT1lemyT

**Comment by khinkelman** [comment]
@laurenklun : would it be possible to link the google doc for the case study draft here? I believe @nllong was setting it up. This would be helpful to not have to search for the file. Thanks!

**Comment by laurenklun** [comment]
@khinkelman  no prob. link to the report format below. 
https://drive.google.com/drive/folders/1nGkdjvPtYpikqntUZH9RNClLbT1lemyT
