### ISSUE TITLE
Please delete master branch (my mistake)

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#23]
The branch name should be "connect_ets_RCbuilding".

**Comment by nllong** [comment]
Oops. I think we want master to just be the latest version of develop, right? Once we release this, then master will be the initial release.

**Comment by nllong** [comment]
I hope to never run this command again 😨 

![image](https://user-images.githubusercontent.com/1907354/71595271-276e0880-2af8-11ea-926a-9909565ca094.png)
