### ISSUE TITLE
Round TimeSeries values

### ISSUE THREAD

**Issue by Helarga** [urbanopt/geojson-modelica-translator#234]
Round the OS and UO SDK time series values of 

1-  Thermal loads [W] to 1 number 
2- Temperature value [degC] to 1 number
3- MassFlowRate value [kg/s] to 3 numbers

this step is to reduce memory storage space as much as possible.

**Comment by vtnate** [comment]
@Helarga 
- Are you referring to the input file from [Amy's measure](https://github.com/urbanopt/geojson-modelica-translator/blob/enhancement/modelica-csv/tests/modelica/data/building_loads.csv)?
- Do you mean total number of digits, or digits after the decimal?

**Comment by Helarga** [comment]
> @Helarga
> 
> * Are you referring to the [file](https://github.com/urbanopt/geojson-modelica-translator/blob/enhancement/modelica-csv/tests/modelica/data/building_loads.csv) from Amy's measure? yes and also any file generated form EP
> * Do you mean total number of digits, or digits after the decimal? digits after the decimal :)

**Comment by vtnate** [comment]
@amyeallen1 When you are working on that DES_HVAC measure, can you also update it to round the output down to fewer digits?

**Comment by amyeallen1** [comment]
Yes, will do. @vtnate

**Comment by vtnate** [comment]
@amyeallen1 Can you include this decimal number change to your measure while you're digging into it?

**Comment by amyeallen1** [comment]
Yes, will do!

**Comment by vtnate** [comment]
@amyeallen1 After thinking about this a bit, it seems like we should make the decimal places be an optional argument the user can pass in, with a default of some large number (10?), so the existing behavior stays the same. What do you think about that idea?

**Comment by amyeallen1** [comment]
Hey Nate, by "existing behavior" do you mean the larger # of decimal places? Is there a particular case in mind where the rounding behavior wouldn't be desired? To me it seems like the rounding to the given # of decimal places would be acceptable in the use cases I can think of, but maybe I'm missing something. @vtnate

**Comment by vtnate** [comment]
@amyeallen1 I can't think of any reason to have a lot of decimal places. I'm all for keeping it simple! Thank you!
