### ISSUE TITLE
[5/13] Expose additional connectors of RC model

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#24]
Currently the wrapper around TEASER RC model only exposes the convective heat port. This issue is for exposing additional connectors that are needed to model HVAC terminal units or to post process computed variables. The additional connectors to expose are:

- `intGainsRad`: Auxiliary port for internal radiative gains
- `ports[nPorts]`: Auxiliary fluid inlets and outlets to indoor air volume
- `QLat_flow`: Latent heat gains for the room
- `TAir`: Indoor air temperature
- `TRad`: Mean indoor radiation temperature

**Comment by nllong** [comment]
Thanks for adding this ticket. I'll start working on this as soon as possible.
