### ISSUE TITLE
GUI organization and layout proposal

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#268]
A proposal for issue #264 

## Background
Modelica users like to open packages in Dymola to view the graphical representation of models. Currently the GMT makes no effort in making this look nice, resulting in models "stacked" on top of each other and confusing connection lines. This is a matter of making sure that the `annotation()` for all icons and connect statements are appropriate.

This issue is a proposal for how we could implement better rendering.

Image for reference to explain the parts
<img width="571" alt="Screen Shot 2020-12-02 at 5 04 20 PM" src="https://user-images.githubusercontent.com/18518728/103037597-3dab7a80-453a-11eb-8507-407306e35f04.png">

The main models in the diagram above are:
- TimeSeries load
- ETS cold water stub (the sup and sink linked to the load)
- heating indirect ETS
- distribution network
- heating plant

To render the timeseries load, we could use this annotation inside of the .mopt file
```python
annotation(Placement(transformation({{ gui.get_transformation(context=model.id, element_id='my_ts_gui_id', element_type='load') }})));
```
Note that my_ts_gui_id is not actually the modelica variable id, but is any locally unique ID used to reference the graphical representation of the element, which is necessary later when we need to refer to it in order to connect it to other elements. the `element_type` arg is required to know the general "shape" (height, width, port offsets) of the element (which we can keep a lookup for in python somewhere else).

The problem with this approach is that we would determine the positioning of elements dynamically. We would rather know the full visual graph, organize it how we like, then fetch positions.

To address this, we could do some magic with the following style
```python
annotation(Placement(transformation({{ gui.transformation.load.my_ts_gui_id }})))
```
Said magic would be to parse variables from the template files and resolve/organize the visual graph _before_ templating, which allows us to make a prettier display. We would use this tool for parsing jinja templates: https://github.com/aromanovich/jinja2schema
Note that the actual jinja variable name/path can be some other style, we just need some type of ID, an indication that we want the icon transformation, and that it should be for a load.

You'd create connect lines with something like this
```python
# first approach
{{ gui.get_line(coupling.id, 'my_component_123', 'another_id_456') }}

# second approach
{{ gui.line.my_component_123__another_component_456 }}
```

The two approaches above require a maintainer to specify GUI things inside of the modelica files themselves (no need to touch python files/classes). The organization of components would be determined with some algorithm. Another approach is to additionally modify our python classes to include information for visual representation. For example, this is how the timeseries load might be updated
```python
class TimeSeriesLoad(BaseLoad):
    gui = {
       'pos': (10, 10), # origin of icon relative to the "load container", ie a box containing the elements rendered for ts
       'components': {
           # type: type of the icon, used to lookup the shape and such (ignore the type names here, not accurate)
           # pos: origin of icon relative to the "load container"
           'sub_comp_a': { 'type': 'real_expression', 'pos': (...) },
           'sub_comp_b': { 'type': 'real_expression', 'pos': (...) },
       }
    }
```
You'd then be able to pretty much use either of the templating apis mentioned above, but we are able to actually know the visual graph structure before we start rendering templates without having to do any template parsing. Another pro is that we can force really strict structuring of components with this approach, e.g. "the real expression should always be right here relative to the load".

The downsides of the class approach:
- we have more information spread across python and modelica files, e.g. you need to use the component IDs defined within the python class. This is kind of not good, and is a bit more tedious every time a maintainer wants to update the modelica files (e.g. add a new component)
- we'd need to define classes for all couplings (currently we only do this for specific models, e.g. loads, ets, network, plant). not ideal b/c that'd be the only reason the class would exist. and more files/code to maintain. Alternatively, we could just say "if a coupling wants to render anything, that thing should probably be its own model and we should break it out".

**Comment by macintoshpie** [comment]
@nllong initial thoughts on how we could handle the visual representation of systems

**Comment by nllong** [comment]
Thanks @macintoshpie for putting this together. Here are my thoughts.

Option 1 and 2 are ideal as the positioning is stored in the modelica file; however, this only makes sense when we are placing unique elements on the grid. For example, take the building loads--imagine having 16 loads that need to be laid out (dynamically). The logic on where those objects are placed would need to live in Modelica, which seems non-ideal. Futhermore, it would really live in the `mot` which is already a layer removed from the modelica world to start with.

Just throwing this out there, what we need is the ability to place static components and "dynamic components". A dynamic component would be a component that can be replicated (extended). (Terminology is negotiable here.) Linkages.js uses a forced grid to determine where components get placed. Maybe we could do something like that too? Then if there is a dynamic component, then there would need to be a parent component with a vectorized input--and within the parent component would be all of the building loads (for example). 

Que piensas?

**Comment by macintoshpie** [comment]
Thanks for the feedback, I think I'm following what you're saying but please let me know if I'm off

> Option 1 and 2 are ideal as the positioning is stored in the modelica file; however, this only makes sense when we are placing unique elements on the grid. For example, take the building loads--imagine having 16 loads that need to be laid out (dynamically).

I think what I've described can handle `n` loads/ets/etc, but maybe there's something I'm missing. I didn't explicitly mention this, but the *_Instance.mopt (where this annotation would live) gets templated for every load/ets/etc required for the district system. This way each one will get its own positioning (ie all model icons positionings are "dynamic", not hardcoded)

For example, in Option 1 we pass the model id (which might be something like `TimSerLoa_abc123uniqueID` to the python method to calculate the position:
```python
gui.get_transformation(context=model.id, ...
```
In Option 2, the specific model "context" is implicit. The python method which is templating the *_Instance.mopt files already knows which model it's templating for, so it would use that information to calculate that model's unique positioning after parsing out the jinja parameters.

What I've described so far is just how we can define an abstract graph of components that need visual representation (and how they're connected) and how we can insert calculated positions into the modelica files. But the process of calculating the positions of the visual components was treated as a black box. I think I agree that placing components on a forced grid makes sense. This is overly simplistic and probably not what we want, but something similar to this idea is what I'm imagining:
<img width="690" alt="Screen Shot 2021-01-28 at 4 37 45 PM" src="https://user-images.githubusercontent.com/18518728/106212167-3c97e980-6187-11eb-8539-14f44ca01af2.png">

In reality it's not just a load and ETS, but also their connected blocks/other signals which would have to be rendered in those dotted squares.

**Comment by macintoshpie** [comment]
## Notes on 1/4/21 Meeting
- This is relevant to the issue of deduplicating/abstracting shared components at the district level (see #290 and #259). We might need to fix those issues before continuing
- 5th gen DHC systems are not going to fit the proposed organization. We currently don't support 5th gen DHC but plan to in the future, so it's worth keeping this in mind with our implementation
- We prefer a representation where "like" are near "like", e.g. we don't want one load at bottom left and one at bottom right. Most preferable are sources (plants) on left and sinks (loads) on right (180 flip of image of previous comment)
