### ISSUE TITLE
Remove connect(weaBus, weaBus) in the generated RC model

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#28]
The generated RC models (e.g. `tests/output/geojson_1/Loads/B5a6b99ec37f4de7f94020090/ICT.mo`) contain an invalid connect statement that needs to be removed:

```connect(weaBus, weaBus)```

**Comment by nllong** [comment]
Nice catch. I’ll fix that.


Da: Antoine Gautier <notifications@github.com>
Risposta: urbanopt/geojson-modelica-translator <reply@reply.github.com>
Data: venerdì 24 gennaio 2020 15:38
A: urbanopt/geojson-modelica-translator <geojson-modelica-translator@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [urbanopt/geojson-modelica-translator] Remove connect(weaBus, weaBus) in the generated RC model (#28)


The generated RC models (e.g. tests/output/geojson_1/Loads/B5a6b99ec37f4de7f94020090/ICT.mo) contain an invalid connect statement that needs to be removed:

connect(weaBus, weaBus)
