### ISSUE TITLE
Need for test for time series (temperature/mass flow rate) model 

### ISSUE THREAD

**Issue by amyeallen1** [urbanopt/geojson-modelica-translator#287]
add (old?) model back and then add test

It seems as though there is no longer a test for the model that uses data in the form of a time series of temperatures and mass flow rates. The current time series test addresses the model that uses this data in this file (time_series_large_office_2013_5B.mos). It would be good to have a test for the time series model using the data in this file (ts_mft_ets_example_data.mos). I recently updated that data, documented in this PR: 
https://github.com/urbanopt/geojson-modelica-translator/pull/285

Thanks, Nate, for identifying this. @vtnate 

Thanks! @nllong @macintoshpie (Tagging you as an FYI, Nick and Ted.)

**Comment by macintoshpie** [comment]
This is blocked by reintegrating the model itself into GMT. Hagar is currently working on an updated version of the modelica model. Once it's added to the GMT we can add this test back.

For more context, this is related to the model `TimeSeriesMassFlowTemperatures.mot` on the `old-design` tag. It was accidentally removed by myself when refactoring the GMT.

**Comment by amyeallen1** [comment]
Thanks, Ted, for the info! @macintoshpie I assigned it to myself as well to remind myself to get the PR reviewed once the test is available.
