### ISSUE TITLE
Refactor unique ID

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#288]
### Expected Behavior
GMT should generate easily identifiable model names, while avoiding naming collisions.

### Actual Behavior
Currently we append a uuid to the end of many variable names that might collide when multiple instances of a model are created. E.g. `my_time_series_load_a02x29`. When you have many models/components it is hard to find the instances of these names.

This uuid is generated like so
```python
def simple_uuid():
    """Generates a simple string uuid

    :return: string, uuid
    """
    return str(uuid4()).split("-")[0]
```

In addition, if a model requires components to be declared _outside_ of the templated modelica model (ie something that's going to be inserted into the district model) then we append the _full_ model name to the end of the variable. The convention is to add an underscore after the typical name, followed by the model's name. For instance, the spawn model requires the declaration of a mass flow rate, so we name it like this:
```modelica
parameter Modelica.SIunits.MassFlowRate mLoaCoo_flow_nominal_{{ model.id }}
```
The same goes for couplings that require additional components, they must use a coupling ID (which is another UUID) to make the declarations unique.

### Version Information

Modelica Buildings Library: `7.0.0 or GithubBranch/SHA (e.g., issue2204_gmt_mbl /SHA_XYZ)`
TEASER: `URBANopt/0.6.9`
Python: `3.6.5`

**Comment by Helarga** [comment]
Based on this comment https://github.com/urbanopt/geojson-modelica-translator/pull/286#discussion_r558374420
