### ISSUE TITLE
Nice to Have: Add hyperlinks within model docs to template source on github

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#295]
As requested by @Helarga (see [here](https://github.com/urbanopt/geojson-modelica-translator/pull/291#issuecomment-768357836)), update our modelica template files with a model annotation to include a hyperlink to the template source on github.

For instance, we should update TimeSeriesBuilding.mot with something like the following annotation:
```modelica
Documentation(
      info="<html>
   ... existing documentation ...
  <p>
    This model was generated by the GeoJSON Modelica Translator from this template:
    <a href="{insert link here}">{insert template name here}</a>
  </p>
   </html>",
```

**Comment by macintoshpie** [comment]
@nllong @Helarga I'm wondering how we should link to the files.

## Option 1
Link directly to the file on the develop branch, e.g.
https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuilding.mot
Downside of this approach is that the template on the branch will probably be different from the one they used to generate the file.

## Option 2
Link directly to the file on a specific tag, e.g.
https://github.com/urbanopt/geojson-modelica-translator/blob/old-design/geojson_modelica_translator/model_connectors/templates/TimeSeriesBuilding.mot
Challenge of this approach is making sure the git tag is written somewhere in the gmt package so we can reference it. But I'm guessing that would just be the same as updating our package version: https://github.com/urbanopt/geojson-modelica-translator/blob/f6d7abf5e4bba20f6ae3b394100c07be1809ed72/setup.py#L57

## Option 3
Link directly to the file on a specific sha, e.g.
https://github.com/urbanopt/geojson-modelica-translator/blob/876b0810b7725d78814b9cf5f380688b17be55e3/geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuilding.mot
Challenge of this approach is pretty much the same as the one for option 2. No real advantages over the tagged link

My vote would option 2

**Comment by Helarga** [comment]
@macintoshpie Option 2 sounds good to me too.

**Comment by nllong** [comment]
not going to address this now. Reopen if needed.
