### ISSUE TITLE
Add assertions on test-generated .mat files

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#296]
### Expected Behavior
GMT tests should assert that the values output by the simulated district model are valid.

### Actual Behavior
GMT tests only assert that the simulation was successfully run by JModelica (ie compiles and can finish without failing)

**Comment by macintoshpie** [comment]
@Helarga @nllong We need to discuss which variables we want to "test". I know Nick mentioned total energy at one point, but I'm not sure where that would be derived.

Just for context, we have access to any (?) component/subcomponent in the district model. For example, `TimeSerLoa_e0ff8fd8.ports_aHeaWat[1].m_flow` and `TimeSerLoa_e0ff8fd8.ports_aChiWat[1].m_flow`
![image](https://user-images.githubusercontent.com/18518728/106323926-78898800-6235-11eb-8871-b91af846d670.png)
(image from model generated by test_district_heating_and_cooling_systems.py)

**Comment by amyeallen1** [comment]
@macintoshpie Hi Ted, that's a good idea. Were you thinking of the check as being a sanity check that certain outputs are reasonable, or comparing to another set of specific values? I think the sanity checks would be useful, and, for the time series-based load models, ensuring that the boundary conditions imposed by the load are met. For sanity checks, we could check that values like mass flow rates and rates of heating delivered  (or heat rejected, if that's defined to be positive) are non-negative, and don't exceed their nominal values by more than a certain fraction, to give a range. 

In the case of the mass flow/temperature time series model, we could compare the supply temperature of the water delivered by the ETS to the supply temperature in the time series file. Per a previous discussion with Hagar, the supply temp delivered by the ETS is in the variable [name of ETS].sta_b2.T. In the ideal case, these two serieses of values are very consistent with each other. We could look at a metric like CV(RMSE) or something else to compare them. 

For the time series loads characterized with values in terms of overall thermal load (W), we could make an analogous comparison between the ETS.q_flow variable and the load time series, to ensure that the load is being met.  @Helarga @nllong  @macintoshpie

**Comment by macintoshpie** [comment]
Thanks @amyeallen1 . I will open a PR adding these tests, probably starting with just the original TimeSeries load first. I wonder which tests we want to add this to? E.g. we have some that don't include plants, some that do, some that are heating or cooling indirect only, etc. Would we want these sanity checks added to all of of them, making assertions only about the parts included in the model? Or just to the full district system models?

> Were you thinking of the check as being a sanity check that certain outputs are reasonable, or comparing to another set of specific values?

I think we just want sanity checks like you mentioned.

> we could check that values like mass flow rates and rates of heating delivered (or heat rejected, if that's defined to be positive) are non-negative, and don't exceed their nominal values by more than a certain fraction, to give a range.

This makes sense, I can implement this first and then we can tweak the fraction for tolerance. I will use mChiWat_flow_nominal and mHeaWat_flow_nominal for the nominal values.

> In the case of the mass flow/temperature time series model, we could compare the supply temperature of the water delivered by the ETS to the supply temperature in the time series file. Per a previous discussion with Hagar, the supply temp delivered by the ETS is in the variable [name of ETS].sta_b2.T. In the ideal case, these two serieses of values are very consistent with each other. We could look at a metric like CV(RMSE) or something else to compare them.

Ok cool, I will use CVRMSE to compare `[name of load].buiMasTem[index of temp]` and `[name of ETS].sta_b2.T` where temp index is the index of the specific heating/cooling temperature time series.

> For the time series loads characterized with values in terms of overall thermal load (W), we could make an analogous comparison between the ETS.q_flow variable and the load time series, to ensure that the load is being met.

So this would be CVRMSE between the ETS's `Q_flow` and the load's `QHea_flow` or `QCoo_flow` depending on the ETS.

Do we also want to check `QHea_flow_nominal` and `QCoo_flow_nominal` to make sure the Q flow stays within a reasonable range like we are mass flow rate?

**Comment by amyeallen1** [comment]
Thanks, Ted! @macintoshpie 

>  I wonder which tests we want to add this to? E.g. we have some that don't include plants, some that do, some that are heating or cooling indirect only, etc. Would we want these sanity checks added to all of of them, making assertions only about the parts included in the model? Or just to the full district system models?

That's a good point. I'll leave it to you and Nick which is a better place to integrate the tests from the software development perspective. I think eventually it would be good to integrate some tests related to the plants' functionality as well, especially with more connected loads and more complex plants. 

> This makes sense, I can implement this first and then we can tweak the fraction for tolerance. I will use mChiWat_flow_nominal and mHeaWat_flow_nominal for the nominal values.

Thanks, Ted!  I will double check with Hagar what variables' values should be compared to these nominal values, unless it's clear to you off hand. I think it would also be worthwhile to perform that check for the "mDis_flow_nominal" set at the ETS (the nominal flow rate on the district side), and I'll also confirm with her what variable's value should be compared to that. 

> Ok cool, I will use CVRMSE to compare `[name of load].buiMasTem[index of temp]` and `[name of ETS].sta_b2.T` where temp index is the index of the specific heating/cooling temperature time series.

Thanks--that sounds good. 

> So this would be CVRMSE between the ETS's `Q_flow` and the load's `QHea_flow` or `QCoo_flow` depending on the ETS.

Yes, exactly. 
> Do we also want to check `QHea_flow_nominal` and `QCoo_flow_nominal` to make sure the Q flow stays within a reasonable range like we are mass flow rate?

Yes, that would be good. I will confirm with Hagar which Q_flow from the ETS should be compared to that.
