### ISSUE TITLE
Templatize CHP and Central Plant Model from CU

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#338]
Jmodelica issue, comment out the test that's failing and then merge down

Mingzhe - generate the district heating and cooling example from the GMT develop branch, take that and add in a CHP plant along side the existing plant. Share the resulting models with us. Try not to make edits or let us know. Ted to assist if needed. 

For the CHP model in the GMT, we plan to use the CHP model from the Buildings library. 

The CHP model 9kW
(ThermalElectricalFollowing.mo) for GMT templatization and a test case (bldsCHPtesting.mo) can be downloaded from Google Drive 
(https://drive.google.com/file/d/1FlHcmSkLTJqBIMv2xPsSKT-27u_LFsr1/view?usp=sharing) 

or Github 
(https://github.com/mingzhe37/Pade-approximant).

This model is from the Buildings library 7.0.0 and the path to it is Buildings/Fluid/CHPs/

Working with Mingzhe on resolving an error. There is a translation setting.

**Comment by vtnate** [comment]
- CHP and central heating plant are combined into one unit now.
    - Old CHP and heating plant files need to be removed.
- New sys-params in `central_heating_plant` that specify if a heating plant is a CHP, and if so, if it is thermal_following or not.
- Running `test_chp_system.py` returns `FMUException: Failed to estimate the directional derivative at time 130.374.` which Mingzhe is helping me troubleshoot.
