### ISSUE TITLE
Add steam to hot water conversion

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#361]
Questions:
- Can we use existing CU steam models? Yes.
- How do we replace plants? Is that possible with different `media`s?
    - probably need to generate one of our existing district models and have someone with modelica expertise edit it, the add changes back into GMT (Could use Ming Zhe's help here)

**Comment by macintoshpie** [comment]
Comment by @amyeallen1 
> we're also going to need to adapt the bldg-level loads, since the modification of the HVAC equipment at the bldg level to operate on HHW instead of steam will also likely change the magnitude of the loads.

**Comment by amyeallen1** [comment]
Thanks, Ted. If you want, I could make a ticket for "Investigate Effect on Bldg Loads from Steam to HHW Conversion and Modify Accordingly" and assign it to myself. @macintoshpie

**Comment by laurenklun** [comment]
Integrate and apply steam models into the GMT. Templatize 1st Generation models once CU's models get into MBL and then onto the GMT staging branch
