### ISSUE TITLE
Rounding TEASER model parameter values

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#37]
TEASER models generated when running `pytest` (e.g. `tests/output/geojson_1/Loads/B5a6b99ec37f4de7f94020090/ICT.mo`) may include parameter values that would better be rounded for readability.

### Expected Behavior

```
  Buildings.ThermalZones.ReducedOrder.RC.TwoElements
  thermalZoneTwoElements(
    redeclare package Medium = Modelica.Media.Air.DryAirNasa,
    VAir=260.9,
    hConvExt=2.05,
    hConvWin=2.70,
    gWin=0.67
```

### Actual Behavior

```
  Buildings.ThermalZones.ReducedOrder.RC.TwoElements
  thermalZoneTwoElements(
    redeclare package Medium = Modelica.Media.Air.DryAirNasa,
    VAir=260.9433707086081,
    hConvExt=2.0490178828959125,
    hConvWin=2.7000000000000006,
    gWin=0.6700000000000002,
```

### Steps to Reproduce

Run `pytest` 

### Version Information

TEASER: `URBANopt/0.7.2`

**Comment by nllong** [comment]
I think we should push this one over to the TEASER team. We could round the values, but really that should be part of TEASER as these values are calculated 'on the fly'.

**Comment by AntoineGautier** [comment]
I agree.

**Comment by nllong** [comment]
closing, as this should be addressed by TEASER itself.
