### ISSUE TITLE
CLI to load Teaser & Spawn [5/30]

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#370]
CLI currently only supports Time Series

**Comment by laurenklun** [comment]
@macintoshpie  Hey Ted, I'm OOO until the 11th. Just wanted to let you know, we're ready for the Spawn work to be integrated into the CLI. Kyle gave the thumbs up. Would you be able to start that late this week or next? 

Not sure if it's work mentioning, we have another analysis project where we're in need of combining time series data on existing buildings with a new Spawn building - "STM Expansion" at NREL's campus . If you could test that case too, it'd be awesome!

FYI, @kbenne @nllong

**Comment by macintoshpie** [comment]
Yep, I will get the current spawn branch merged, then start on the cli 👍  I can have the CLI probably up and running with spawn by the end of next week.

Hmm I'm not sure I totally understand the "STM Expansion" task, but I will chat with the others to see what needs to be done. Thanks!
