### ISSUE TITLE
Suggested modification for heating hot water supply temperature

### ISSUE THREAD

**Issue by amyeallen1** [urbanopt/geojson-modelica-translator#401]
To modify the heating hot water supply temperature setpoint, the user needs to modify the value in [this template ](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/couplings/templates/Network2Pipe_HeatingPlant/ComponentDefinitions.mopt#L10) as well as the building-level setpoint value in the coupling template for the load model type ([this](https://github.com/urbanopt/geojson-modelica-translator/blob/01c893c0d899c39a213d209c09ab76970802b0a0/geojson_modelica_translator/model_connectors/couplings/templates/Teaser_HeatingIndirect/ComponentDefinitions.mopt#L13) as an example for TEASER). It would be nice if these water-side setpoint values for both heating and cooling could be populated based on the system design parameters schema.

**Comment by nllong** [comment]
From my understanding there isn't a way at the moment to templatize values in the `.mopt` files. We can only using the coupling object in these files, which don't have access to the system parameter data. Is that right @macintoshpie ? 

If that is the case, then the only option would be to use Modelica Builder to change the value after the fact--something like [this](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/load_connectors/teaser.py#L438-L448)

**Comment by macintoshpie** [comment]
@nllong @amyeallen1 That's correct, you cannot put user provided parameters into mopt files currently. The limitation is self-imposed (ie not b/c we can't in the code). I was trying to isolate user-provided data into models themselves and out of the district-system level b/c of edge cases for when parameters are or are not required (we weren't always building the full district system previously, we had stubbed ETSes, networks, etc)

Ideally we could move these things into the models themselves so that they could then be templatized, @amyeallen1 do you think that's possible?

**Comment by amyeallen1** [comment]
Thanks, Nick and Ted, for thinking about this. "Move into the models themselves" as in move into the .mot templates as opposed to the .mopt templates? I don't see any .mot files associated with the network itself, but perhaps this value could go in the DistrictEnergySystem.mot file, since it's a district-level setpoint value. And, perhaps the setpoint could be propagated from the HHW plant. model. I don't think I've grasped all the implications of setting a value in one template vs another, so perhaps we could talk about this more during the next scrum. 

@nllong @macintoshpie

**Comment by macintoshpie** [comment]
#415 adds system parameters to the mopt files that are relevant to loads. But _not_ to mopt files that are not load-specific (e.g. the coupling files between networks and heating plants).
e.g. if you wanted to add this to the network/heating plant component mopt file
```
Modelica.Blocks.Sources.RealExpression TDisSetHeaWat_{{ coupling.id }}(
    each y=273.15+{{ sys_params.ets_model_parameters.indirect.heating_supply_water_temperature_district }})
    "District side heating water supply temperature set point."
    ...
```
Then which "building" in the sys params do you pass to the template (ets_model_parameters is part of the building definition in sys params)?

For the load-specific couplings, we know which building data from sys params to pass, which is what #415 is doing ([example see here](https://github.com/urbanopt/geojson-modelica-translator/blob/bc980480d96662231f8393efe10ce041e81371c1/geojson_modelica_translator/model_connectors/districts/district.py#L131)).

For non-load specific couplings, I think we can either:
1. pass the default building (and also require that a default is always defined)
2. pass the `district_system` part of the sys params - requiring us to move or duplicate the data we want to include currently
3. pass the entire system parameters dictionary into the template context (but then in the template how do you select which building data to use?)

@nllong @amyeallen1 @vtnate Thoughts on the above?

**Comment by vtnate** [comment]
I think we should pass the `district_system` block, and use that as motivation to clean up our parameters.

**Comment by amyeallen1** [comment]
I agree with Nate--we should use the district_system block for the district-level setpoints, ideally instead of setting those at the ETS. I don't think we have any use cases in which we would want the ability to set separate district-side setpoints for an individual ETS.

**Comment by macintoshpie** [comment]
Thanks yall, if there's no use case for different district-side setpoints for individual ETSes then I suggest we do the following:
1. refactor the sys params schema so heating and cooling setpoints for district side is in district_system
2. refactor places that referenced the original location in sys params to use the new location in sys params
3. refactor district.py to pass the `district_system` block to coupling mopt files

@vtnate do you want to tackle 1 and 2 in a separate PR first?
