### ISSUE TITLE
weather file from SDK workflow in .mos

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#410]
~Wetbulb .mos file is a different ticket.~

the weather file has to be set manually right now when using the SDK CLI workflow. It should be an input to the CLI so the file doesn't have to be edited by hand afterwards.

-Nate and Amy to consult 

-Hiccup with CVOde in simulation

**Comment by vtnate** [comment]
@nllong  Is [this](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/data/spawn_system_params_ex1.json#L36) what we're referring to? The CLI only supports (at this time) `time series` models, not `spawn` models (or teaser, or anything else). We'll need to update the CLI to support additional models.

**Comment by laurenklun** [comment]
I'm pretty sure it was using the time series loads. @Zahra-Fallahi, could you send a link to that weather file discrepancy you found between the SDK and GMT while doing the 4G models?

**Comment by nllong** [comment]
> @nllong Is [this](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/data/spawn_system_params_ex1.json#L36) what we're referring to? The CLI only supports (at this time) `time series` models, not `spawn` models (or teaser, or anything else). We'll need to update the CLI to support additional models.

I think think ticket is adding the ability to specify which weather file to use via the CLI. Something like:
```
uo_des build-sys-param sys_param.json baseline_scenario.csv example_project.json --weather ~/weather/denver.mos
```

**Comment by Zahra-Fallahi** [comment]
the issue was that while creating the system parameter file, the correct weather file was not written by GMT. I think GMT should adapt the weather file input from the feature file. 
https://github.com/Shoussai/STM-Expansion/tree/DES is the link to the project I was working on. 

I ended up using MBL to convert my EPW to mos, but I believe they can be directly downloaded from https://energyplus.net/weather.

**Comment by nllong** [comment]
I see, yes, if we already have the data in the UO feature file, then we should use that. It would be a simple file extension switch from EPW to MOS.

And yup, we added all the MOS files for the US to energyplus.net last year!

**Comment by vtnate** [comment]
@Zahra-Fallahi, can you add some detail to the issue above with what you want to accomplish? The time_series sys-param files don't have any weather files besides the [mos_wet_bulb_filename](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/data/time_series_system_params_ets.json#L116), which looks like a different ticket (which ticket?). Should we add a weather file to this schema and figure out how to use weather from these sys-param files?

**Comment by Zahra-Fallahi** [comment]
@vtnate 

1- uo_des build-system-param should look into the feature file for the appropriate name of the weather file. 
2- There should be a warning for user if the .mos file is not available for their location. 
3- alternatively, the uo-des can look into the weather folder of the UO project and convert the relevant epw to mos, but I am not sure if this is in the scope of the work.

**Comment by vtnate** [comment]
@Zahra-Fallahi Thanks. Those 3 steps are not too difficult. However, since this ticket is explicitly not about the mos wetbulb file, I'm not sure what to do with the weather file after we grab it for a time_series modelica model. Where are you using the mos weather file in your existing time series modelica models?

**Comment by Zahra-Fallahi** [comment]
I am not sure if I am writing in the right issue. However, the selection of the correct mos file is important for the operation of the cooling tower.

**Comment by vtnate** [comment]
Thanks @Zahra-Fallahi. I think the mos_wetbulb weather file is this ticket, given what you've said.

My interpretation is that getting the mos weather file from the sdk weather folder and accessing it [here](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/model_base.py#L157-L158) is what we need to do. I'll have the cli ask the user for the weather file name and will use that to populate the `mos_wet_bulb_filename` entry in the sys-param file.

@nllong @laurenklun can either of you confirm this is what we're trying to do?

**Comment by nllong** [comment]
Yes on "I'll have the cli ask the user for the weather file name and will use that to populate the mos_wet_bulb_filename entry in the sys-param file.". Also, update the mos_weatherfile if we need to as well.
