### ISSUE TITLE
System Parameters does not reflect in Modelica model

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#430]
These parameters do not change TimeSeries in the modelica file when changed in the systems param file

Check Loads, ETS, Districts. 

- temp_hw_supply
- temp_hw_return
- heating_supply_water_temperature_districs
- heating_supply_water_temperature_building
- heat_flow_nomina. also think about limits on pressure drop? 

Working for TEASER and Spawn?

-Ted has developed a script to ID the system parameters not used in the example file for an L3 case.

**Comment by macintoshpie** [comment]
After our discussion today (@laurenklun @nllong @Zahra-Fallahi and Jiazhen), a few questions/concerns were raised:
- on `develop` the parameter `heating_supply_water_temperature_districts` is no longer in the schema.json.
- temp_hw_supply seems to modify the modlica component of interest (see [here](https://github.com/urbanopt/geojson-modelica-translator/blob/c1d97295c004f15c2fc84065de81e17b6b05c6d6/geojson_modelica_translator/model_connectors/couplings/templates/Network2Pipe_HeatingPlant/ComponentDefinitions.mopt#L10))
- we might be adding 273.15 TWICE to `heating_supply_water_temperature_building` - or maybe it's not getting used correctly at all?? More investigation needs to be done.


In general, this is prompted a concern about 
- documentation/clean up of sys parameters schema and example sys param files
- validity/usage of sys params in our template models (are we using them, are the units being converted correctly, etc)

There was an additional (possibly unrelated, though I'm not sure) discussion around the temperature in a timeseries model going to below 0C. One recommendation was checking the room pressure.

**Comment by macintoshpie** [comment]
This is a work in progress, but I've created a method for determining if a sys param affects the final model at all. TLDR; I start with an example geojson and sys params, iterate through the sys params tweaking values as I go, and compare that to the untweaked model to find file diffs.

Here's a partially finished run of the process
https://gist.github.com/macintoshpie/80793cd11eff6f5b376e3adff37b3253

You can find the branch with the script etc here:
https://github.com/urbanopt/geojson-modelica-translator/commit/3bf96bc4b59342ee442ba83d4006eaa5de8ab7c1

**Comment by laurenklun** [comment]
@jiazhenling here's a few things to look out for in the 4G heating and cooling model

**Comment by nllong** [comment]
Sweet, thanks for documenting and bringing this script to the foreground again. Is [this script](https://github.com/urbanopt/geojson-modelica-translator/commit/3bf96bc4b59342ee442ba83d4006eaa5de8ab7c1#diff-0e84a502247468cd43dabdfce074c401fb1608246dfd475bcb0b5636a072e5ca) part of the repo? Maybe we should make a CI task that runs this all the time?

**Comment by macintoshpie** [comment]
@nllong for the other ticket (https://github.com/urbanopt/urbanopt-modelica/issues/118) I'm turning it into a command you can run
