### ISSUE TITLE
.mos files need DHW time series for 5th gen models

### ISSUE THREAD

**Issue by vtnate** [urbanopt/geojson-modelica-translator#442]
### Expected Behavior
[These load files](https://github.com/urbanopt/openstudio-prototype-loads/tree/develop/loads) need an additional column for DHW energy consumption values.
### Actual Behavior
Column does not exist yet

**Comment by nllong** [comment]
It appears that the column exists, right? 

```
#Peak space cooling load = -517373.5 Watts
#Peak space heating load = 119999.1 Watts
#Peak water heating load = 0 Watts
double tab1(8760,4)
0;-43903.1;5124.2;0.0
3600;-56686.4;4447.6;0.0
7200;-52067.5;4557.9;0.0
10800;-47733.7;5481.9;0.0
14400;-44027.3;5939.0;0.0
18000;-40066.0;7390.5;0.0
21600;-36201.8;8692.2;0.0
```

But the data are all 0. Shouldn't that still work though with the 5G system?

**Comment by vtnate** [comment]
Did I go crazy? You are totally correct, though I have vivid memories of not finding the column and manually adding it in a test file and having success. I will close this with the assumption that it wasn't ever a valid concern. Geeze.

**Comment by vtnate** [comment]
Did I go crazy? You are totally correct, though I have vivid memories of not finding the column and manually adding it in a test file and having success. I will close this with the assumption that it wasn't ever a valid concern. Geeze.
