### ISSUE TITLE
UO End to End Example (GeoJSON to Multiple TEASER Bldgs w/ Static District Supply)

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#45]
Est Completion: ?

o	Need to try and run the translator on a generic geojson file from URBANopt. Ask Katherine for a reasonable file to start with. Run it through the translator and figure out what is missing.
o	If everything just works, then we need to demonstrate why this all matters, which speaks to creating a single design alternative for now. Perhaps that is a 4GDHC vs a 5GDHC system. 

We need to get an exemplar GeoJSON from the URBANopt UI project that has, let’s say, 10 buildings in that. We need to make sure that we can translate that into a fully articulated Modelica model with 10 buildings (some can be RC models and some can be Spawn). The buildings should be connected to ETS systems and connected to an infinite source district system.

**Comment by laurenklun** [comment]
Yanfei and LK to work together

**Comment by YanfeiNREL** [comment]
yes, the ETS branch rebase was completed. Nick helped a lot!!! There were some weird problems there. rebase_template_ets branch has no Modelica-Buildings-Lib included. But it looks like when rebasing into develop branch, the whole Modelica-Buildings-Lib shows up again. Nick helped resolved it.

**Comment by YanfeiNREL** [comment]
Thanks for assigning me the task. A couple questions: (1) what does it mean generic geojson? (2) what model do i ask from Katherine?

**Comment by nllong** [comment]
This has been superseded by more granular tasks. (#71, #75)
