### ISSUE TITLE
List of Parameters That Should Be Configurable by user in GeoJSON

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#46]
List available in slide 6&7 in presentation

Est Completion: 3/20

**Comment by amyeallen1** [comment]
This is complete in draft form, subject to modification through further group discussion. (Slides 6 and 7 in this presentation: https://docs.google.com/presentation/d/1m-IhkOwR7FQy0Umkh_PQmCrT3KVV7M8UJ7U0do9R2nc/edit#slide=id.g71a354b2bc_2_12)
