### ISSUE TITLE
Workflow to Run Jmodelica on HPC Modelica Translator

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#47]
Est Completion: 4/30

**Comment by nllong** [comment]
@amyeallen1 is this complete?

**Comment by amyeallen1** [comment]
@nllong Thanks for bringing this up. Yes, the thing itself is, but I haven't written up formal documentation. I'll do that and send it to you and Brian.

**Comment by nllong** [comment]
Okay, yeah, a simple doc (on drive or a README in one of the repos) should suffice. Thanks amy.
