### ISSUE TITLE
CLI example producing error: MODELICAPATH

### ISSUE THREAD

**Issue by NicholasFry** [urbanopt/geojson-modelica-translator#470]
### Expected Behavior
From example: https://urbanopt-tutorial.s3.amazonaws.com/videos/12_DES_Tutorial.mp4
![image](https://user-images.githubusercontent.com/60554125/169874217-d2657026-02cd-4823-a9b1-5e25e54f9e6a.png)
min 12:29
Should produce:
![image](https://user-images.githubusercontent.com/60554125/169874379-a10ee926-5625-4910-99f6-55d29e2bf16b.png)

### Actual Behavior
Produces error and unknown message for DEBUG on path:
![image](https://user-images.githubusercontent.com/60554125/169874512-c0cefde4-70af-4c4e-ac4e-d7dfc0c2e487.png)

### Steps to Reproduce
Assign environmental variables for MODELICAPATH with the following:
C:\Users\[USERNAME]\Documents\GitHub\geojson-modelica-translator\tests\management\data\sdk_project_scraps\model_from_sdk
and
C:\Users\[USERNAME]\Documents\GitHub\modelica-buildings;

### Version Information
URBANOpt 0.8.0
Python 3.10.2

EDIT:

Also tried virtual environment containing Py 3.8 and Py 3.7 with the same results. I assume this has something to do with the local Docker installation, but I do not have any ideas on how to resolve it at this point.

**Comment by NicholasFry** [comment]
Update: I have uninstalled docker desktop. I have disabled WSL 2 on windows 11. I have reinstalled docker desktop. All updates on WSL are visible for today's date in the file explorer (shown). After running a new pipenv with python 3.8, 
![image](https://user-images.githubusercontent.com/60554125/171066341-e8d34794-40f1-46d6-ac43-385767892024.png)
I have added every dependency I can think of directly to the venv without any change in result. Pip list shown.
![image](https://user-images.githubusercontent.com/60554125/171066401-151f9a6e-ee5e-4184-b984-733ad5665391.png)
Any suggestions?

**Comment by vtnate** [comment]
We are working on a fix for this. Until we release the fixed version, please use GMT v0.2.2 and MBL v7.x.

**Comment by vtnate** [comment]
Simulations can be run with GMT v0.5.0 and MBL v9.1.0! OpenModelica has been integrated into the GMT and models can now be simulated seamlessly. As both OpenModelica and the GMT are still under development, some capabilities may not be available or fully completed. Please continue to provide GMT feedback here.
