### ISSUE TITLE
Correct parameter names in generated RC models

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#51]
### Actual Behavior

The generated RC models have incorrect parameter names.
Examples are taken from `tests/output/geojson_1/Loads/B5a6b99ec37f4de7f94020090/Floor.mo`.

- `hConvExt` should be `hConExt`.
- `hConvWin`...
- `hConvInt`...
- `hConvWallOut`...
- `hConvWinOut`...

Note: The convention in MBL (as much as possible) is to truncate to 3 characters the different patterns in the Camel case notation (except for physical quantities or other variables that have a standard symbol). Here the convention is actually violated for `Wall` which is unfortunate...

IN ADDITION

All instances should be renamed according with the new naming conventions.

- `Modelica.Blocks.Sources.Constant alphaWall` should rather be `Modelica.Blocks.Sources.Constant hConWall`.

### Steps to Reproduce

Run `pytest`.

### Version Information

Modelica Buildings Library: `7.0.0`
TEASER: `0.7.2`
Python: `3.7.6`

**Comment by nllong** [comment]
This seems like an issue with TEASER itself. https://github.com/RWTH-EBC/TEASER/search?q=hConvExt&unscoped_q=hConvExt. We can update it on our end and wait for TEASER to catchup?
