### ISSUE TITLE
Update GMT to accept GHE parameters and network configurations

### ISSUE THREAD

**Issue by JingWang-CUB** [urbanopt/geojson-modelica-translator#511]
This issue is for creating new templates and tests for 5G district energy systems with geothermal heat exchangers under the URBANopt GHP project.

**Comment by JingWang-CUB** [comment]
@vtnate , could you please create a new branch based on the current develop branch named issue511_ghe_templates for me to put my new templates and stuff? Thanks!!

**Comment by vtnate** [comment]
@JingWang-CUB Done! https://github.com/urbanopt/geojson-modelica-translator/tree/issue511_ghe_templates

**Comment by vtnate** [comment]
Closed with #533
