### ISSUE TITLE
Update names of Buildings.ThermalZones.ReducedOrder.RC.TwoElements parameters

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#6]
The ROM parameters `alphaInt, alphaExt`, etc. have been renamed in the last version of Buildings.  This is to update the export.

**Comment by AntoineGautier** [comment]
@nllong When do you think you can update to the new version of Buildings? (I am stuck with that issue when trying to build an example with 2 building models.)

**Comment by nllong** [comment]
Let me look at this tomorrow (Thursday). I’ll need to update the teaser
library as well (not a huge deal).

Il giorno mer 18 set 2019 alle 12:02 Antoine Gautier <
notifications@github.com> ha scritto:

**Comment by nllong** [comment]
Pulling in the changes from this list: https://github.com/modelica-3rdparty/Buildings/blob/ba97b6e539c31138d353d0d05aebb63ebb58f0e3/Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_6_to_7.0.0.mos

**Comment by nllong** [comment]
@AntoineGautier  -- Okay, this has been completed by using an updated TEASER library. See PR #7
