### ISSUE TITLE
Enable user configuration of loop pump nominal head pressure

### ISSUE THREAD

**Issue by vtnate** [urbanopt/geojson-modelica-translator#609]
### Expected Behavior

Users should be able to set the head pressure of the district pump

- It should be added to the schema, probably for both 4th and 5th gen systems. So, [here](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/system_parameters/schema.json#L1193) and [here](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/system_parameters/schema.json#L1224).
- Then it should be added into a test file, like [here](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/data_shared/system_params_des_5g.json#L129), and a test should be made (or an assertion added to an existing test) that checks that it gets read and used properly.

### Actual Behavior

It's hard-coded [here](https://github.com/urbanopt/geojson-modelica-translator/blob/mblv10/geojson_modelica_translator/model_connectors/networks/templates/NetworkDistributionPump_Instance.mopt#L25). A larger district would be too much for this pump setting, causing a modelica simulation failure.

### Version Information

Modelica Buildings Library: `10.0.0`
Modelica Standard Library: `4.0.0`
Python: `3.11.7`

**Comment by JingWang-CUB** [comment]
Hi @tanushree04 , can you please add the "pump_design_head" parameter to "central_pump_parameters" under the 4th and 5th gen system schema? An example can be found here: https://github.com/urbanopt/geojson-modelica-translator/pull/610/files#. Let me know if you have any questions.
