### ISSUE TITLE
ETS Template is requiring files incorrectly

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#64]
The ETS template and related tests are requiring files in strange ways. For example:
```
base_folder = os.path.join(os.getcwd(), "geojson_modelica_translator")
        dest_path = "/system_parameters/schema.json"
        self.system_parameters_geojson = base_folder + dest_path
```
The schema.json file should not be read other than using an instance of the `system_parameters` file. This most likely relates to #62 since the schema is incorrect, I suspect that the ETS template is reading value from the schema and not an instance.

Furthermore, string replacements like this need to be verified.

```
 self.thermal_junction_properties_geojson = self.thermal_junction_properties_geojson.replace("\\", "/")
```

Data are being written to the tests folder that are actually being used in the ETS model
```
directory_up_two_levels = os.path.abspath(os.path.join(__file__, "../../.."))
        self.directory_ets_templated = os.path.join(
            directory_up_two_levels + "/tests/output_ets"
        )
```

**Comment by nllong** [comment]
It appears that the ETSTemplate class is not actually used... can we delete @YanfeiNREL ?

**Comment by YanfeiNREL** [comment]
which branch is this? Actually ETSTemplate class is being used. I need to double check

**Comment by YanfeiNREL** [comment]
Initially ETSTEmplate was used in my own unit-test file: test_ets.py. Then later i changed it to geojosn_modelica_translator.py and test_translator.py. The latest status is i am trying in integrate into scaffold/to_modelica().

**Comment by nllong** [comment]
moved to #98. File still exists, but need to update after #96 and #97
