### ISSUE TITLE
[5/12] Connect Terminal Unit to RC Model

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#68]
Create a template for RC building model for connecting terminal units and flow distribution
Add unit test to exercise this functionality (TEASER)
Nick will do Spawn verification (urbanopt/geojson-modelica-translator#59)

Completed for:
Spawn (verify unit test)

Date: 14 April

**Comment by laurenklun** [comment]
@nllong Yanfei finished this one. Please see branch: connect_terminal_RC_13buildings. 

@YanfeiNREL

**Comment by nllong** [comment]
Is there a PR for this?

**Comment by nllong** [comment]
@YanfeiNREL -- is there a PR for this update?

**Comment by laurenklun** [comment]
@YanfeiNREL  How's it coming with resolving the unit tests and conflict?

**Comment by YanfeiNREL** [comment]
Thanks for checking. I am still working on it.
