### ISSUE TITLE
[6/12] Run UO Example Project with Spawn

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#72]
1) get the example project to work w/ TEASER. *complete
2) get to work w/ Spawn *complete

.idf files needed from Katherine/Rawad
put into repo for example project

Update systems parameters file to point to these files correctly

currently works w/ TEASER

Initial Evaluation: 17 April

**Comment by vtnate** [comment]
- Ensure example geojson file matches the one used by uo sdk
- troubleshoot/debug test_uo_teaser_project.py, which uses that gj file
- copy test to new spawn folder, run with spawn, troubleshoot/debug that
- Add a ModelicaRunner test - it's marked with a todo in the code
