### ISSUE TITLE
Update GMT to use Modelica Builder Package

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#76]
Remove existing package manipulation and replace with modelica builder

Date Complete: 15 April

**Comment by laurenklun** [comment]
@macintoshpie Hi Ted, would you be able to complete this issue by Friday? @nllong

**Comment by macintoshpie** [comment]
Hi Laruen, I think that is doable. I've already integrated it locally, but running the tests it turned out to be very slow. So now I'm working on refactoring it to improve performance.

@nllong we should chat about how publish the package

**Comment by nllong** [comment]
I think we should publish (and incorporate) using git checkout in the requirements.txt file for now. That work?
