### ISSUE TITLE
Ensure idf file names are unique 

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#9]
This is needed until [#1566](https://github.com/lbl-srg/modelica-buildings/issues/1566) is closed (@mwetter working on it).
The two exported models simulate **together** only when modifying the `idf` files names so that they are different (the absolute paths being different is not sufficient).

**Comment by AntoineGautier** [comment]
@nllong Consider this issue on hold for now because @mwetter might be able to solve #1566 within a week.

**Comment by nllong** [comment]
Sounds good. On hold.

**Comment by nllong** [comment]
@AntoineGautier are we still on hold for this?

**Comment by mwetter** [comment]
@nllong : We can now use the same idf file name for multiple buildings.

**Comment by nllong** [comment]
closing per last comment
