### ISSUE TITLE
Further cleanup of system parameter schema

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#97]
* Make system parameter schema elements snake_case
* Add units to the description field in the schema
* Make the elements required in the schema
* Update the system parameters files with ETSs with the update schema names
* Address this hack: <>. I really don’t want to use arrays in this, so let me know if we can remove the hack. If this is needed, then we need to decide how to deal with this in the JSON Schema.
* Update any other code as needed

**Comment by YanfeiNREL** [comment]
For the array hack,  i found that "for loop" statement is a major feature within Jinja 2. For example:
`{% for item in seq -%}
    {{ item }}
{%- endfor %}
 '
In this snippet, it means seq is a list. 
################################################
In our case, for example ets-template:
`
{% for x in ets_data['q_flow_nominal'] %}
  parameter Modelica.SIunits.HeatFlowRate Q_flow_nominal(
    final min=0,
    start={{ x  }})
    "Nominal heat transfer"
     annotation(Dialog(group="Heat exchanger"));
  {% endfor %}
`  
It means ets_data['q_flow_nominal' =[12.3]. Thus we have to use array. 
#########################################################
However, i explored and found an solution for above template file: 
`
{% raw %}
parameter Modelica.SIunits.HeatFlowRate Q_flow_nominal(
    final min=0,
{% endraw %}
    start={{ ets_data['q_flow_nominal']  }})
    {% raw %}
    "Nominal heat transfer"
     annotation(Dialog(group="Heat exchanger"));
     {% endraw %}
`  
This solution has more {%raw%} and {%endraw%} for the chuck we want to reserve in templating. 
########################################################################
Hopefully above are helpful.
